[formatter.clang-format]
command = "clang-format"
options = [
  "-i",
]
includes = [
  "*.c",
]

[formatter.mdformat]
command = "mdformat"
includes = [
  "*.md",
]

[formatter.nix]
command = "nix"
options = [
  "fmt",
]
includes = [
  "*.nix",
]

[formatter.shfmt]
command = "shfmt"
options = [
  "--write",
]
includes = [
  "*.sh",
  ".envrc",
]

[formatter.toml-sort]
command = "toml-sort"
includes = [
  "*.toml",
]

[formatter.yamlfmt]
command = "yamlfmt"
includes = [
  "*.yaml",
  "*.yml",
  ".clang-format",
]

[formatter.yamllint]
command = "yamllint"
includes = [
  "*.yaml",
  "*.yml",
  ".clang-format",
]

[global]
excludes = [
  "*.build",
  "*.gitignore",
  "*.ini",
  "*.lock",
  "*.options",
  ".editorconfig",
  "LICENSE.md",
]
